# Generated by Django 2.0.5 on 2018-05-21 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('strength', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('tiles', models.ManyToManyField(blank=True, related_name='weapons', to='room.Tile')),
            ],
        ),
    ]
