# Generated by Django 2.0.5 on 2018-05-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='agility',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='tiles',
            field=models.ManyToManyField(blank=True, null=True, related_name='weapons', to='room.Tile'),
        ),
    ]
