# Generated by Django 2.0.5 on 2018-05-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0002_auto_20180522_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='tiles',
            field=models.ManyToManyField(blank=True, related_name='weapons', to='room.Tile'),
        ),
    ]
