# Generated by Django 2.0.5 on 2018-05-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0003_auto_20180522_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapons', models.ManyToManyField(blank=True, related_name='inventories', to='gear.Weapon')),
            ],
        ),
    ]
