# Generated by Django 2.0.5 on 2018-05-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0004_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='reach',
            field=models.IntegerField(default=0),
        ),
    ]
