# Generated by Django 2.0.5 on 2018-05-22 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20180522_1745'),
        ('gear', '0005_weapon_reach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Untitled', max_length=255)),
                ('ability', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.Ability')),
            ],
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='tiles',
        ),
        migrations.AddField(
            model_name='weapon',
            name='ability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='status.Ability'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='weapons',
            field=models.ManyToManyField(blank=True, to='gear.Weapon'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='consumables',
            field=models.ManyToManyField(blank=True, to='gear.Consumable'),
        ),
    ]
