# Generated by Django 2.0.5 on 2018-05-23 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0006_auto_20180522_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumable',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.Ability'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='ability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='status.Ability'),
        ),
    ]
