# Generated by Django 2.0.5 on 2018-05-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
