# Generated by Django 2.0.5 on 2018-05-22 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20180522_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability',
            name='action',
            field=models.CharField(choices=[('MH', 'MinorHealPotion')], default='MH', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ability',
            name='range',
            field=models.IntegerField(default=0),
        ),
    ]
