# Generated by Django 2.0.5 on 2018-05-22 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0003_auto_20180522_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='action',
            field=models.CharField(choices=[('MH', 'MinorHeal')], max_length=2),
        ),
    ]
