# Generated by Django 2.0.5 on 2018-05-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0005_auto_20180523_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='action',
            field=models.CharField(choices=[('MH', 'MinorHeal'), ('SR', 'SafeRoom')], max_length=2),
        ),
    ]
