# Generated by Django 2.0.5 on 2018-05-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0006_auto_20180524_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='action',
            field=models.CharField(choices=[('MH', 'MinorHeal'), ('SR', 'SafeRoom')], default='MH', max_length=2),
        ),
    ]
