# Generated by Django 2.0.5 on 2018-05-22 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_player_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='abilities',
            field=models.ManyToManyField(blank=True, null=True, to='status.Ability'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Unnamed', max_length=255),
        ),
        migrations.AlterField(
            model_name='player',
            name='tile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room.Tile'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gear.Weapon'),
        ),
    ]
