# Generated by Django 2.0.5 on 2018-05-22 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20180522_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='abilities',
            field=models.ManyToManyField(blank=True, to='status.Ability'),
        ),
    ]
