# Generated by Django 2.0.5 on 2018-05-22 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_auto_20180522_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='inventory',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gear.Inventory'),
        ),
        migrations.AlterField(
            model_name='player',
            name='tile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='room.Tile'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weapon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equiped_set', to='gear.Weapon'),
        ),
        migrations.AddField(
            model_name='group',
            name='black_list',
            field=models.ManyToManyField(blank=True, related_name='black_lists', to='player.Player'),
        ),
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='player.Player'),
        ),
        migrations.AddField(
            model_name='group',
            name='white_list',
            field=models.ManyToManyField(blank=True, related_name='white_lists', to='player.Player'),
        ),
    ]
