# Generated by Django 2.0.5 on 2018-05-23 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0007_auto_20180522_2102'),
        ('player', '0007_auto_20180522_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='room.Room'),
            preserve_default=False,
        ),
    ]
