# Generated by Django 2.0.5 on 2018-05-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_auto_20180523_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='desired_action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
