# Generated by Django 2.0.5 on 2018-05-24 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_auto_20180523_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gear.Inventory'),
        ),
    ]
