# Generated by Django 2.0.5 on 2018-05-24 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_auto_20180524_0209'),
        ('player', '0011_auto_20180524_0018'),
    ]

    operations = [
    ]
