# Generated by Django 2.0.5 on 2018-05-21 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_east', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_west', to='room.Room')),
                ('room_north', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_south', to='room.Room')),
                ('room_south', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_north', to='room.Room')),
                ('room_west', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_east', to='room.Room')),
            ],
        ),
        migrations.CreateModel(
            name='Tile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coord', models.IntegerField()),
                ('y_coord', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room.Room')),
            ],
        ),
    ]
