# Generated by Django 2.0.5 on 2018-05-21 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0002_tile_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_east',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_west', to='room.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_north',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_south', to='room.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_south',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_north', to='room.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_west',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_east', to='room.Room'),
        ),
    ]
