# Generated by Django 2.0.5 on 2018-05-21 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_auto_20180521_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='looked',
            field=models.BooleanField(default=False),
        ),
    ]
