# Generated by Django 2.0.5 on 2018-05-22 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_tile_looked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='room.Room'),
        ),
    ]
