# Generated by Django 2.0.5 on 2018-05-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_auto_20180522_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='grid_size',
            field=models.IntegerField(default=5),
        ),
    ]
