# Generated by Django 2.0.5 on 2018-05-24 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0008_room_round_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='round_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
