# Generated by Django 2.0.5 on 2018-05-22 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enemy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='abilities',
            field=models.ManyToManyField(blank=True, null=True, to='status.Ability'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='loot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gear.Weapon'),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='name',
            field=models.CharField(default='Unnamed', max_length=255),
        ),
        migrations.AlterField(
            model_name='enemy',
            name='tiles',
            field=models.ManyToManyField(blank=True, null=True, related_name='enemies', to='room.Tile'),
        ),
    ]
