# Generated by Django 2.0.5 on 2018-05-22 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enemy', '0003_auto_20180522_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='loot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enemies', to='gear.Weapon'),
        ),
    ]
