# Generated by Django 2.0.5 on 2018-05-22 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gear', '0004_inventory'),
        ('enemy', '0004_auto_20180522_0344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enemy',
            old_name='loot',
            new_name='weapon',
        ),
        migrations.AddField(
            model_name='enemy',
            name='health',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='enemy',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enemies', to='gear.Inventory'),
        ),
    ]
