# Generated by Django 2.0.5 on 2018-05-24 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enemy', '0008_auto_20180524_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enemy',
            name='enemy_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enemy.EnemyType'),
        ),
    ]
