# Generated by Django 2.0.5 on 2018-05-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enemy', '0010_auto_20180524_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemytype',
            name='health',
            field=models.IntegerField(default=10),
        ),
    ]
